import { Question } from '../model/types';

export const MOCK_QUESTIONS: Question[] = [
  {
    id: 1,
    title: 'React에서 useEffect의 의존성 배열은 언제 사용하나요?',
    summary:
      'useEffect를 사용할 때 의존성 배열을 비워두는 경우와 값을 넣는 경우의 차이를 알고 싶습니다.',
    hashtags: ['React', 'JavaScript', 'Hooks'],
    likeCount: 23,
    viewCount: 342,
    answerCount: 5,
    isResolved: true,
    createdAt: '2025-02-20T10:00:00Z',
    updatedAt: '2025-02-20T10:00:00',
    user: {
      id: 101,
      nickname: '개발초보',
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=q1',
      cohort: 8,
    },
  },
  {
    id: 2,
    title: 'TypeScript에서 제네릭을 사용하는 이유가 무엇인가요?',
    summary: '제네릭의 개념과 실제 프로젝트에서 어떻게 활용하는지 궁금합니다.',
    hashtags: ['TypeScript', 'Generic'],
    likeCount: 45,
    viewCount: 567,
    answerCount: 8,
    isResolved: true,
    createdAt: '2025-02-19T15:30:00Z',
    updatedAt: '2025-02-19T15:30:00',
    user: {
      id: 102,
      nickname: '타입마스터',
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=q2',
      cohort: 7,
    },
  },
  {
    id: 3,
    title: 'Git에서 rebase와 merge의 차이점은 무엇인가요?',
    summary:
      '협업할 때 rebase를 쓰라는 말을 들었는데, merge와 어떤 차이가 있는지 모르겠습니다.',
    hashtags: ['Git', 'Version Control'],
    likeCount: 67,
    viewCount: 892,
    answerCount: 12,
    isResolved: true,
    createdAt: '2025-02-18T09:15:00Z',
    updatedAt: '2025-02-18T09:15:00',
    user: {
      id: 103,
      nickname: '깃린이',
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=q3',
      cohort: 9,
    },
  },
  {
    id: 4,
    title: 'Next.js에서 getStaticProps와 getServerSideProps의 차이',
    summary:
      'SSG와 SSR의 차이는 알겠는데, 실무에서 어떤 상황에 어떤 것을 써야 할지 모르겠습니다.',
    hashtags: ['Next.js', 'React', 'SSR', 'SSG'],
    likeCount: 34,
    viewCount: 445,
    answerCount: 6,
    isResolved: true,
    createdAt: '2025-02-17T11:20:00Z',
    updatedAt: '2025-02-17T11:20:00',
    user: {
      id: 104,
      nickname: '넥스트러',
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=q4',
      cohort: 6,
    },
  },
  {
    id: 5,
    title: 'Docker 컨테이너와 이미지의 차이를 쉽게 설명해주실 수 있나요?',
    summary: 'Docker를 공부하고 있는데 컨테이너와 이미지의 개념이 헷갈립니다.',
    hashtags: ['Docker', 'DevOps'],
    likeCount: 18,
    viewCount: 234,
    answerCount: 3,
    isResolved: false,
    createdAt: '2025-02-16T14:45:00Z',
    updatedAt: '2025-02-16T14:45:00',
    user: {
      id: 105,
      nickname: '도커초보',
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=q5',
      cohort: 10,
    },
  },
];
